theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core March 2019 RNA-Seq Workshop @ UCSF '
tagline: 'June 18th-22nd, 2018'
name: 'UC Davis Bioinformatics Core March 2019 RNA-Seq Workshop @ UCSF '
github:
  repository_url: https://ucdavis-bioinformatics-training.github.io/2019_March_UCSF_mRNAseq_Workshop
